version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-k8#m9@x7v2$n4p!q6w8e+r5t7y9u=i1o3p5a7s9d1f3g5h7j9k2l4n6m8b0v2c4x6z8
      - DEBUG=False
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    command: >
      sh -c "python manage.py migrate &&
             python create_admin.py &&
             python manage.py collectstatic --noinput --clear &&
             gunicorn --bind 0.0.0.0:8000 temple_attendance.wsgi:application"